version: '3.8'

services:
  mailarchive-app:
    image: s1t5/mailarchiver:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - ${HTTP_PORT}:5000
    networks:
      - mail_net
    secrets:
      - source: mail_app_settings
        target: /app/appsettings.Production.json
    volumes:
      - mail_data_keys:/app/DataProtection-Keys
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: MailArchiver
      POSTGRES_USER: mailuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - mail_net
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailuser -d MailArchiver"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mail_net:
    driver: overlay

volumes:
  mail_data_keys:
    external: true
    name: ${VOLUME_NAME_DATA_KEYS}
  postgres_data:
    external: true
    name: ${VOLUME_NAME_DATA}

secrets:
  mail_app_settings:
    external: true
  db_password:
    external: true